testing gainagain

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -13,25 +13,24 @@ jobs:
     #clone the github to the runner system
       - uses: actions/checkout@v4
 
-      - name: move into source
-        run: cd Source 
-
-      - name: look at FILE_PATH
-        run: ls -a
+      - name: check file
+        run: |
+          cd Source 
+          ls -a
 
       # Read the Target.cs file and make sure it has the correct unreal engine version
       - name: Check Unreal Engine target version in Target.cs file
         run: |
-         FILE_PATH="./Source/TimeParadox.Target.cs"
+         FILE_PATH="Source/TimeParadox.Target.cs"
 
          if[-f "$FILE_PATH"] then
 
-          if grep -q "IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_4;" "$FILE_PATH"; then
-            echo "Project correctly configured to run on UE5"
-          else
-            echo "Error: Project not configured to run on UE5"
-            exit 1
-          fi
+            if grep -q "IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_4;" "$FILE_PATH"; then
+              echo "Project correctly configured to run on UE5"
+            else
+              echo "Error: Project not configured to run on UE5"
+              exit 1
+            fi
 
 
 
